name: Check Links
on:
  workflow_dispatch: # Manual checks
  schedule:
    - cron: 31 13 * * 2 # 13:31 on Tuesdays

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        env:
          FORCE_COLOR: 0
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: node packages/gscan/test/valid-doc-links.js
