name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - 'renovate/*'
jobs:
  test:
    uses: tryghost/actions/.github/workflows/test.yml@0ae9e7106ad098932c6b71dbf54e71d31cecc7ec
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
