name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - 'renovate/*'
jobs:
  test:
    name: Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        env:
          FORCE_COLOR: 0
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - run: yarn
      - run: yarn test
